name: CI/CD Pipeline
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DS_TOKEN }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
          
      - name: Build project
        run: npm run build
          
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Autobuild: ${{ github.run_number }}" || echo "No changes to commit"
          
      - name: Add safe directory
        run: git config --global --add safe.directory /github/workspace
          
      - name: Push changes
        run: |
          git remote set-url origin https://${{ secrets.DS_TOKEN }}@github.com/Adam-DS23/reader2-edu.git
          git push origin HEAD:main --force
